### ISSUE TITLE
Allow hiding the javascript view.

### ISSUE THREAD

**Issue by afraser** [snookca/CoffeeConsole#11]
I use CoffeeConsole primarily as a console when the commands I want to run are longer and more involved. The javascript pane isn't really helping me out most of the time, so I'd love to be able to hide it.

**Comment by hilko** [comment]
Seconded. I've come to rely on CoffeeScript but I stopped needing to see the js output most of the time. Being able to hide it, especially when working on my tiny 11" screen, would be really great!
