### ISSUE TITLE
Make this work like a real console

### ISSUE THREAD

**Issue by paulmillr** [snookca/CoffeeConsole#2]
- ↩ should execute code, ⇧↩ should add new line
- Result of execution should be on the next line
- `console.log` etc should be before the result of execution
- Add autocomplete (not a big deal)

**Comment by christiangenco** [comment]
I like ↩ running code and ⇧↩ adding a new line; feels very familiar.

The problem with the result being on the next line is that you miss seeing how your coffeescript compiled to javascript. What if the flow looked like this:

```
$ alert "hello"   # coffeescript
> alert("hello"); # javascript
  undefined       # result of expression
$                 # new coffeescript prompt
```

The compiled javascript could be coloured differently and/or collapsable.

**Comment by paulmillr** [comment]
As for javascript, we could just mirror it on the right, just as we doing it now. Because it's not all the time you want to see js output.

For example, i'm using console often for page scripting:

``` javascript
[].slice.call(document.querySelectorAll('.meh')).map(function(element) {return element.innerText})
```

With CS this can be reduced to `[$$('.meh')...].map((element) -> element.innerText)`

**Comment by snookca** [comment]
I didn't have it execute on Enter because I'm anticipating that people may be more apt to do longer pieces of code. In Firebug, I always switched to the expanded console for this reason. However, if enough people wanted it switched, it could be easily switched.

As for the console, I didn't want to rewrite the entire console output. There's already a console and it's possible to have the console output open along with CoffeeConsole. Chrome has a console API but it's still in the experimental phase, which requires end users to have to change a flag to be able to install the app. I might revisit the console output when the API is no longer experimental.

**Comment by ricardobeat** [comment]
@paulmillr I did exactly what want on my fork, with reasonable success. As @snookca said, the console API is still in it's infancy and not even available without setting a flag on your browser.

**Comment by paulmillr** [comment]
@ricardobeat I don't really care if it enabled only by flag or not, we're developers, right?

By the way, just tried your fork: awesome job, dude! DOM things don't seem to work though.

`Object has too long reference chain(must not be longer than 1000)` on `document.querySelectorAll('.comment')`

Could you open an issue tracker in your fork?

**Comment by christiangenco** [comment]
@ricardobeat YES! Ahh this is so beautiful.

I second @paulmillr's request for an issue tracker; there's a handful of bugs keeping me from switching to this console full time.

**Comment by ricardobeat** [comment]
@christiangenco @paulmillr Issues open.

_edit:_ upon looking at the issue, I realized I'm heading to a dead end. Unless the console API exposes a whole bunch of methods, including rendering, we're looking at mimicking a huge amount of functionality (think Firebug Lite). @snookca's approach of re-using the standard console is far saner for now.

I'll look into hooking into the actual console tab via the `--debug-devtools-frontend` flag to add CoffeeScript support directly into it.

**Comment by paulmillr** [comment]
I made a real coffeescript console here: https://github.com/paulmillr/firefox-jsterm (might be merged to https://github.com/paulrouget/firefox-jsterm soon)
